const myExerciseList = [
    {id: 1, exerciseType: 'Abs', name: 'Crunches'},
    {id: 2, exerciseType: 'Abs', name: 'Leg Raise'},
    {id: 3, exerciseType: 'Back', name: 'Pull Up'},
    {id: 4, exerciseType: 'Back', name: 'Cable Row'},
    {id: 5, xerciseType: 'Back', name: 'Dumbell Row'},
    {id: 6, exerciseType: 'Biceps', name: 'Preacher Curl'},
    {id: 7, exerciseType: 'Biceps', name: 'EZ-Bar Curl'},
    {id: 8, exerciseType: 'Biceps', name: 'Alternating Dumbell Curl'},
    {id: 9, exerciseType: 'Calves', name: 'Smith Machine Calf Raise'},
    {id: 10, exerciseType: 'Calves', name: 'Dumbell Calf Raise'},
    {id: 11, exerciseType: 'Chest', name: 'Barbell Flat Bench Press'},
    {id: 12, exerciseType: 'Chest', name: 'Barbell Incline Bench Press'},
    {id: 13, exerciseType: 'Chest', name: 'Dumbell Flat Bench Press'},
    {id: 14, exerciseType: 'Chest', name: 'Dumbell Incline Bench Press'},
    {id: 15, exerciseType: 'Forearm', name: 'Dumbbell Wrist Flexion'},
    {id: 16, exerciseType: 'Glutes', name: 'Conventional Deadlift'},
    {id: 17, exerciseType: 'Glutes', name: 'Cable Glute Kickback'},
    {id: 18, exerciseType: 'Glutes', name: 'Glute Bridge'},    
    {id: 19, exerciseType: 'Hamstrings', name: 'Lying Leg Curl Machine'},     
    {id: 20, exerciseType: 'Hamstrings', name: 'Nordic Curls'},  
    {id: 21, exerciseType: 'Hamstrings', name: 'Medicine Ball Leg Curl'},  
    {id: 22, exerciseType: 'Lats', name: 'Lat Pull Down Machine'},  
    {id: 23, exerciseType: 'Lats', name: 'Cable Striaght-Arm Pull-Downs'}, 
    {id: 24, exerciseType: 'Lats', name: 'Dumbbell Rows'}, 
    {id: 25, exerciseType: 'Quadriceps', name: 'Seated Leg Extensions'}, 
    {id: 26, exerciseType: 'Quadriceps', name: 'Sissy Squat'}, 
    {id: 27, exerciseType: 'Quadriceps', name: 'Front Squats'},
    {id: 28, exerciseType: 'Shoulders', name: 'Seated Dumbbell Overhead Press'},
    {id: 29, exerciseType: 'Shoulders', name: 'Cable Lateral Raise'},
    {id: 30, exerciseType: 'Shoulders', name: 'Arnold Press'},
    {id: 31, exerciseType: 'Traps', name: 'Shrugs'},
    {id: 32, exerciseType: 'Triceps', name: 'Cable Tricep Extension'},
    {id: 33, xerciseType: 'Triceps', name: 'Skull Crushers'},
    {id: 34, exerciseType: 'Triceps', name: 'Dips'},
]


export default myExerciseList